version: "3.9"

networks:
  app-net:

services:
  etcd:
    image: bitnamilegacy/etcd:3.4.9
    container_name: etcd
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    ports:
      - "2379:2379"
    networks:
      - app-net
    volumes:
      - ./volume/etcd_data:/etcd_data:777

  apisix:
    image: apache/apisix:3.14.1-debian
    container_name: apisix
    restart: always
    volumes:
      - ../configs/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9180:9180/tcp"
      - "9080:9080/tcp"
      - "9091:9091/tcp"
      - "9443:9443/tcp"
    networks:
      - app-net

  apisix-dashboard:
    image: apache/apisix-dashboard:2.15.1-alpine
    container_name: apisix-dashboard
    volumes:
      - ../configs/apisix/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    restart: always

    depends_on:
      - etcd
    ports:
      - "9000:9000"
    networks:
      - app-net
