version: "3.9"

networks:
  app-net:

services:
  # Service name, used as the hostname for your Go application connection string
  postgres_db:
    image: postgres:15-alpine # Using a lightweight image for development
    container_name: rbac_postgres_db
    restart: always
    ports:
      # Maps local port 5432 to the container's PostgreSQL port
      - "5432:5432"
    environment:
      # Custom database environment variables (update these for production)
      POSTGRES_USER: queuesystem
      POSTGRES_PASSWORD: qweQWE123!@#
      POSTGRES_DB: queuesystem
      # Optional: Set the timezone to UTC for consistency
      TZ: "UTC"
    volumes:
      # Persists the PostgreSQL data across container restarts
      - postgres_data:/var/lib/postgresql/data
      # Mount the migrations folder so a migration tool (like golang-migrate or goose) can access them
      # Uncomment the line below if your migration tool needs direct access to the files inside the DB container
      # - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - app-net

  user-service:
    build:
      context: ..
      dockerfile: deployments/http-service.Dockerfile
    container_name: user-service
    environment:
      JWT_SECRET: test-secret
      LOG_LEVEL: info
      DATABASE_URL: postgres://queuesystem:qweQWE123!%40%23@postgres_db:5432/queuesystem?sslmode=disable
    ports:
      - "8081:80"
    networks:
      - app-net
    depends_on:
      - postgres_db
    volumes:
      - ../api/user-service.yaml:/app/api/user-service.yaml
    command: ["./http-service", "user-service", "-p", "80"]

  auth-service:
    build:
      context: ..
      dockerfile: deployments/http-service.Dockerfile
    container_name: auth-service
    environment:
      JWT_SECRET: test-secret
      LOG_LEVEL: info
      DATABASE_URL: postgres://queuesystem:qweQWE123!%40%23@postgres_db:5432/queuesystem?sslmode=disable
    ports:
      - "8080:80"
    volumes:
      - ../api/auth-service.yaml:/app/api/auth-service.yaml
    networks:
      - app-net
    depends_on:
      - postgres_db
    command: ["./http-service", "auth-service", "-p", "80"]

volumes:
  postgres_data:
